import { buildPermissionKey } from "./roles.catalog";

export const APP_PERMISSION_KEYS = {
  posAccess: buildPermissionKey("POS", "Operacion POS", "Acceder al modulo Facturar"),
  salesCreate: buildPermissionKey("POS", "Operacion POS", "Crear ventas desde POS"),
  salesChangeCustomer: buildPermissionKey("POS", "Operacion POS", "Cambiar cliente en la factura"),
  salesManagePayments: buildPermissionKey("POS", "Operacion POS", "Gestionar pagos en efectivo, transferencia y combinado"),
  salesHistory: buildPermissionKey("POS", "Operacion POS", "Ver historial de ventas"),
  salesPrint: buildPermissionKey("POS", "Operacion POS", "Imprimir factura"),
  cashOpen: buildPermissionKey("POS", "Caja y control diario", "Abrir caja"),
  cashClose: buildPermissionKey("POS", "Caja y control diario", "Cerrar caja"),
  cashView: buildPermissionKey("POS", "Caja y control diario", "Consultar resumen de caja"),
  productsView: buildPermissionKey("Contabilidad", "Items, inventario y contactos", "Ver listado de items"),
  productsCreate: buildPermissionKey("Contabilidad", "Items, inventario y contactos", "Crear nuevos items de venta"),
  productsEdit: buildPermissionKey("Contabilidad", "Items, inventario y contactos", "Editar items"),
  productsDelete: buildPermissionKey("Contabilidad", "Items, inventario y contactos", "Eliminar items"),
  stockMovesView: buildPermissionKey("Contabilidad", "Items, inventario y contactos", "Ver listado de ajustes de inventario"),
  purchasesView: buildPermissionKey("Contabilidad", "Compras y proveedores", "Ver listado de facturas de proveedores"),
  purchasesDetails: buildPermissionKey("Contabilidad", "Compras y proveedores", "Ver detalles de facturas de proveedores"),
  purchasesCreate: buildPermissionKey("Contabilidad", "Compras y proveedores", "Crear nuevas facturas de proveedores"),
  suppliersView: buildPermissionKey("Contabilidad", "Items, inventario y contactos", "Ver listado de proveedores"),
  suppliersCreate: buildPermissionKey("Contabilidad", "Items, inventario y contactos", "Agregar nuevos contactos"),
  suppliersEdit: buildPermissionKey("Contabilidad", "Items, inventario y contactos", "Editar contactos"),
  usersView: buildPermissionKey("Configuraciones generales", "Usuarios y seguridad", "Ver usuarios"),
  usersCreate: buildPermissionKey("Configuraciones generales", "Usuarios y seguridad", "Crear usuarios"),
  usersEdit: buildPermissionKey("Configuraciones generales", "Usuarios y seguridad", "Editar usuarios"),
  rolesView: buildPermissionKey("Configuraciones generales", "Usuarios y seguridad", "Ver roles y permisos"),
  rolesManage: buildPermissionKey("Configuraciones generales", "Usuarios y seguridad", "Administrar el rol Administrador"),
  customersView: buildPermissionKey("Contabilidad", "Items, inventario y contactos", "Ver listado de clientes"),
  customersCreate: buildPermissionKey("Contabilidad", "Items, inventario y contactos", "Agregar nuevos contactos"),
  customersEdit: buildPermissionKey("Contabilidad", "Items, inventario y contactos", "Editar contactos"),
  correspondentView: buildPermissionKey("POS", "Operacion de tienda", "Gestionar corresponsal"),
  reportsView: buildPermissionKey("Contabilidad", "Reportes comerciales y financieros", "Ver reporte de ventas generales"),
  settingsView: buildPermissionKey("Configuraciones generales", "Negocio y sistema", "Editar configuracion general del negocio"),
} as const;
